{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | kebabcase }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name | kebabcase }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
    {{- if $svc.grpcPort }}
    - name: grpc
      port: {{ $svc.grpcPort }}
      targetPort: grpc
    {{- end }}
  {{- end }}