apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{application="$${__span.tags["peer.service"]}"} | json | traceId="$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: Request rate
            query: 'rate(http_server_requests_seconds_count{application="$${__span.tags["peer.service"]}"}[1m])'