apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceId
          matcherRegex: '"traceId":"(\w+)"'
          url: http://localhost:16686/trace/${__value.raw}
          datasourceUid: jaeger